### PR TITLE
Issue 44: Added color key to static calendar

### PR DESCRIPTION
**Pull request by sahilthakur3029**
Added moffitt and doe color legend to the title of static calendar RFAL @leebianca @bdeleonardis1

### CODE REVIEW

**Comment by bdeleonardis1** [comment]
@leebianca the design for this doesn't look amazing imo, can you make some suggestions for improvement.

**Comment by sahilthakur3029** [comment]
;(

**Comment by bdeleonardis1** [comment]
Looks good to me, let's just make it a little prettier when Bianca makes her suggestions.

**Comment by leebianca** [comment]
Could you guys move the legend under the week heading so that they're not in the two different corners?

**Comment by bdeleonardis1** [comment]
@sahilthakur3029 I think you and me have about the same design ability :) @leebianca can you just fix this and merge it. Here's the changes I think it would make it better, but you know best:
- Get rid of No Shift it's obvious
- Move Doe under Moffitt
- Get rid of colon, add a space and vertically the color box

**Comment by sahilthakur3029** [comment]
;(

**Pull request merged**
